# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0002_auto_20160105_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='trading_day',
            field=models.CharField(default=2009, max_length=10),
            preserve_default=False,
        ),
    ]
