# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0003_data_trading_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='aclose_price',
        ),
    ]
