# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0007_auto_20160106_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='v',
        ),
    ]
