# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0008_remove_data_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='volume',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
