# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0009_data_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 7, 18, 10, 28, 787225, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
