# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0011_auto_20160107_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiftyday',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 1, 7, 21, 11, 51, 864841, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiveday',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 1, 7, 21, 12, 0, 810041, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twohundredday',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 1, 7, 21, 12, 7, 746998, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
