# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0012_auto_20160107_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='trading_day',
        ),
    ]
