# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0014_auto_20160108_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='movingavg',
            name='span',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
