# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0016_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='series',
            field=models.CharField(default='n', max_length=10),
            preserve_default=False,
        ),
    ]
