# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0017_movement_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movement',
            new_name='Movements',
        ),
    ]
