# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0018_auto_20160118_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='percent_move',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
