# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0019_movements_percent_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='Means',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('series', models.CharField(max_length=10)),
                ('span', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Significance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('series', models.CharField(max_length=10)),
            ],
        ),
    ]
