# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0020_means_significance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movements',
            old_name='percent_move',
            new_name='percent',
        ),
    ]
