# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketgrab', '0021_auto_20160210_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sigma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('series', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Means',
        ),
        migrations.DeleteModel(
            name='Significance',
        ),
        migrations.AddField(
            model_name='movements',
            name='zvalue',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
